### PR TITLE
Expose BCW options for caching

### PR DESCRIPTION
**Pull request by knownasilya**
Only recompile if sass or scss files change.

### CODE REVIEW

**Comment by simonexmachina** [comment]
The RegExp should be `/\.(sass|scss)$/i`, but otherwise LGTM.

**Comment by stefanpenner** [comment]
I'm curious why unrelated files are in the actively developed style tree. I suspect my
Recent fixes to cli and bcw will mitigate this need.

I'm fine if a user can opt into this, but don't think it should be enabled by default. Since other file types can be encoded into sass output.

More perf work is planned, and will continue to make improvement here without this fix being enabled by default for everyone

**Comment by simonexmachina** [comment]
I agree. @knownasilya the way to provide this feature is to expose the `cacheInclude` option. Then users can specify that RegExp if they want.

**Comment by knownasilya** [comment]
Probably worth exposing the exclude option as well.

**Comment by knownasilya** [comment]
@aexmachina Made the changes to this PR to just expose the options.

**Comment by simonexmachina** [comment]
Nice one, thanks!

**Comment by simonexmachina** [comment]
Published v1.5.0

**Pull request merged**
