### PR TITLE
Make this package implementation-agnostic

### LINKED ISSUE #26: Add support for Dart Sass
Dart Sass is in Release Candidate phase now, with a full release probably coming next week. It would be great to add support to this package for choosing between Node Sass and Dart Sass. I'm willing to create a pull request, but I'm not sure what the best design would be.

Right now, this package has a `nodeSass` option that can be configured, but because it includes Node Sass in its dependencies, this still requires users to get Node Sass even if they want to use Dart Sass—which is often be a big pain, since that can involve building C code. One way around this would be to remove Node Sass as a dependency and require users to pass in the version of the compiler they want to use, either using the existing API or using something like

```js
var sass = require('broccoli-sass-source-maps')(require('dart-sass'));
```

### PR DESCRIPTION
**Pull request by nex3**
Rather than always loading Node Sass, this now requires users to pass in
either Dart Sass or Node Sass as an option to the plugin.

Closes #26

### CODE REVIEW

**Comment by simonexmachina** [comment]
Thanks @nex3, that all looks good to me 👍 However I think it would be prudent to add a CHANGELOG that makes it clear to anyone using this directly that the `require` usage has changed in v3.

**Comment by nex3** [comment]
Done!

**Comment by simonexmachina** [comment]
Thanks @nex3. I'm guessing this should be released as a new major version.

**Comment by simonexmachina** [comment]
Published as v4.0.0 👍 Thanks :) I'll try to be quicker with the subsequent PRs :)

**Pull request merged**
