### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by stefanpenner**
- upgrade broccoli-caching-writer
- improve promise usage
- add semi-colons for performance

once https://github.com/ember-cli/broccoli-caching-writer/pull/58 we will get a nice little boost.
More talk about performance: https://github.com/aexmachina/ember-cli-sass/issues/74

### CODE REVIEW

**Comment by stefanpenner** [comment]
There is an easy way to get much better performance. Currently, everything in bower_components/vendor and app are *considered* when determining if a rebuild is needed or not.

Now this means stuff "magically" works, but this means as an app and vendor grow. Copious time is spent merely figuring out if some input file changed or not.

We have several options, likely worth exploring. Most affective would be:

1. only watch `app/styles` by default
2. give users an API to add additional "input paths"

An example API could be:

```js
var app = new EmberApp()
app.options.cssMatchers.concat([
  this.app.name + '/styles/**/*.sass',
  'bower_components/material-design-lite-src/src/**/*.scss'
]);
```

**Comment by simonexmachina** [comment]
Haha, yeah those semicolons should really turbocharge those codes. That code style was actually inherited from broccoli-sass, with the goal of merging back at some point in the future. But I think that this module will just be closed if and when broccoli-sass gets source maps support again, so I'm okay with the deviation.

**Comment by simonexmachina** [comment]
Hey Stef, would you like to be a collaborator on this project? I'm working in native mobile land at the moment, so it's difficult for me to devote much time to Ember stuff.

**Comment by simonexmachina** [comment]
Shouldn't there be a package.json update too?

**Comment by simonexmachina** [comment]
Doesn't look like this is ready for release yet?

**Comment by stefanpenner** [comment]
Sure, I'll gladly help maintain.

Oops ya I needed to update package.json. I guess I Linked locally.

The unreleased part of bcw aren't needed. They will merely be a nice additive improvement (no API change)

**Comment by simonexmachina** [comment]
Okay is this a major, minor or patch update to bssm?

I'll add you to the Github and NPM packages now.

**Comment by simonexmachina** [comment]
That's done.

**Comment by stefanpenner** [comment]
This one should be minor version bump

**Comment by simonexmachina** [comment]
I've published v1.3.0.

**Comment by simonexmachina** [comment]
Should I push an update to ember-cli-sass? Be aware that I'm relying on your testing!

**Comment by stefanpenner** [comment]
> Should I push an update to ember-cli-sass? Be aware that I'm relying on your testing!
>   Delete branch

lets wait to add tests to both the repos, likely better to do that anyways.

I was making these changes in an app, so it continued to work. But if we get regressions in the wild, i would much rather fix them against a test suite. I'll try to make some time over the next few days.

**Comment by simonexmachina** [comment]
Amen to that!​

**Pull request merged**
