### PR TITLE
[fixes #14] don’t write map, if sourceMaps are embedded

### LINKED ISSUE #14: don't write map file, if sourceMaps are embedded
https://github.com/aexmachina/broccoli-sass-source-maps/blob/master/index.js#L73-L75

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by simonexmachina** [comment]
I didn't think they were necessarily mutually exclusive, but I agree that this is a reasonable decision.

**Comment by simonexmachina** [comment]
Published v1.5.1.

**Comment by stefanpenner** [comment]
I only noticed because livereload reloads the whole page if a map file changes. Trolling my sass hot reloading

**Comment by simonexmachina** [comment]
Aha! Cool, thanks.

**Comment by stefanpenner** [comment]
@aexmachina i suppose you will be excited to know the next version of CLI will include hot-reload of css and images

**Comment by simonexmachina** [comment]
Yes indeed! I noticed that. Very cool, nice one :+1:

**Pull request merged**
