### PR TITLE
Update broccoli-caching-writer to use ^3.0.3

### PR DESCRIPTION
**Pull request by huiyuan**

### CODE REVIEW

**Comment by simonexmachina** [comment]
Thanks. Why is this required?

**Comment by stefanpenner** [comment]
@aexmachina just keeping stuff up to date.

**Comment by simonexmachina** [comment]
👍

**Comment by simonexmachina** [comment]
Does this require a major version increment of this module?

**Comment by huiyuan** [comment]
@aexmachina I don't think it's required, can you release please?

**Comment by simonexmachina** [comment]
Yes will do when I get off this train :)

**Comment by simonexmachina** [comment]
Pushed v1.8.1.

## 

_Simon Wade_

aexmachina.info
github.com/aexmachina
twitter.com/aexmachina
linkedin.com/pub/simon-wade/1/a34/566

**Pull request merged**
